<?php

/**
 * Returns the importmap for this application.
 *
 * - "path" is a path inside the asset mapper system. Use the
 *     "debug:asset-map" command to see the full list of paths.
 *
 * - "entrypoint" (JavaScript only) set to true for any module that will
 *     be used as an "entrypoint" (and passed to the importmap() Twig function).
 *
 * The "importmap:require" command can be used to add new entries to this file.
 *
 * This file has been auto-generated by the importmap commands.
 */
return [
    'app' => [
        'path' => './assets/app.js',
        'entrypoint' => true,
    ],
    'admin_users' => [
        'path' => './assets/script/admin/users.js',
        'entrypoint' => true,
    ],
    'admin_movies' => [
        'path' => './assets/script/admin/movie.js',
        'entrypoint' => true,
    ],
    'admin_photos' => [
        'path' => './assets/script/admin/photos.js',
        'entrypoint' => true,
    ],
    'test_users' => [
        'path' => './assets/script/test/users.js',
        'entrypoint' => true,
    ],
    'jquery' => [
        'version' => '3.7.1',
    ],
    '@popperjs/core' => [
        'version' => '2.11.8',
    ],
    'bootstrap/dist/css/bootstrap.min.css' => [
        'version' => '5.3.2',
        'type' => 'css',
    ],
    'bootstrap' => [
        'version' => '5.3.2',
    ],
    'alpinejs' => [
        'version' => '3.13.3',
    ],
    'validate.js' => [
        'version' => '0.13.1',
    ],
    'toastr' => [
        'version' => '2.1.4',
    ],
    'toastr/build/toastr.min.css' => [
        'version' => '2.1.4',
        'type' => 'css',
    ],
    'tui-pagination' => [
        'version' => '3.4.1',
    ],
    'tui-pagination/dist/tui-pagination.min.css' => [
        'version' => '3.4.1',
        'type' => 'css',
    ],
    'lodash' => [
        'version' => '4.17.21',
    ],
    '@reduxjs/toolkit' => [
        'version' => '2.2.3',
    ],
    'redux' => [
        'version' => '5.0.1',
    ],
    'immer' => [
        'version' => '10.0.4',
    ],
    'reselect' => [
        'version' => '5.1.0',
    ],
    'redux-thunk' => [
        'version' => '3.1.0',
    ],
    'vue/dist/vue.esm-browser.js' => [
        'version' => '3.4.24',
    ],
];
